language: node_js
node_js:
  - 8
  - 6
env:
  secure: zWg8iz8zMiYTIuiafVYuZosMk+QStm5Ty0prxOEqMgHuszvMRcL52cEvJ3979PHHmL3spNnyGlqbe4cOLHRxvGBArbSvQNIDb566QiWV1xz+ZscyN3AMJsSp79IzwNRYL5nKbsyZGTjt1FSELF6pUfzAD3D6jqpa8jMK4rt07e3WPnB0D1Ej0eIqVju7Qkq8MlP8B16WhLIBLErsFU+OQqf+SfO0xAELiFrBbK6jlO0C1sSI7xXL53o/sS/fcGTzdXM3Rnr4AWBr8YRAKScfHES5X3XnIG2OpO7pcyaWNKvHg3l75SPwz1VWi5TuI6DHRYIkDv3MxIbOPcP/ovg6XBlk6k3jtj/BuwujXw/SjroJkr3UjC48IcSotI7xQBCSLMu3/28L4Tizcx9uIE4DkxkyOtf3RRLiawz0vZQxC6kaWgfgPgKPNQB69XRr8osLq6ZipF+u+cWUCWLUpL+sgy6Rq/+jY+wezfQomASiFv/qaoLLjosGCDDHZXkTkIuNGf/hpri2PxZKWgQauv+2zC2h1p7+JYASy6zh2gyR4rRfGjaI76rCbz7NohP3t+HyEC+L/IHAT2S6o502V+T8m5f9tEzSvZVhsI/R4nXsfF+3UlEaUTjud/561snGlpqj0HlkxdRwl3DdCH6Pj1SwmgtnFsIFms3k9NQYpBrF3EA=
